### ISSUE TITLE
delete_assignments.py - 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by geographicus** [Esri/workforce-scripts#31]
I'm trying to run an unaltered copy of the _delete_assignments.py_ script, with the ArcGIS Pro 2.2 Python default install, and am getting the following error:

python delete_assignments_MG.py -u MYUSERNAME -p THEPASSWORD -org "https://OURORG.maps.arcgis.com" -project-id "efb4cb86b3514eefb64a9a31d6b6e329" -log-file "../logs/deletedAssignments.log" -where "1=1"
[2018-08-27 12:49:16,273] [      delete_assignments.py:  55 -                           main()]             [MainThread] [      root] [    INFO] Authenticating...
[2018-08-27 12:49:19,410] [      delete_assignments.py:  93 -                       <module>()]             [MainThread] [      root] [CRITICAL] Exception detected, script exiting
[2018-08-27 12:49:19,412] [      delete_assignments.py:  94 -                       <module>()]             [MainThread] [      root] [CRITICAL] 'NoneType' object is not subscriptable
[2018-08-27 12:49:19,418] [      delete_assignments.py:  95 -                       <module>()]             [MainThread] [      root] [CRITICAL] Traceback (most recent call last): |   File "delete_assignments_MG.py", line 91, in <module> |     main(args) |   File "delete_assignments.py", line 64, in main |     project = workforce.Project(item) |   File "C:\Users\giesbm\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\apps\workforce\project.py", line 45, in __init__ |     self._assignment_schema = AssignmentSchema(self.assignments_layer) |   File "C:\Users\giesbm\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\_impl\common\_utils.py", line 95, in _lazy_property |     setattr(self, attr_name, fn(self)) |   File "C:\Users\giesbm\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\apps\workforce\project.py", line 216, in assignments_layer |     return FeatureLayer(self.assignments_layer_url, self.gis) |   File "C:\Users\giesbm\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\apps\workforce\project.py", line 166, in assignments_layer_url |     return self._item_data['assignments']['url'] | TypeError: 'NoneType' object is not subscriptable |

Running from command line with:
 - OS: Win 10 64bit
 - Python Version: 3.6.5

I do have records in the assignments table, is enabled for editing, allowing others to export, etc.

**Comment by apulverizer** [comment]
@geographicus Can you verify the project id is correct and pointing to a Workforce project and not a webmap or some other item?

**Comment by geographicus** [comment]
@apulverizer - Perfect!  Thanks for pointing that out, as I was using the ID of the assignments layer.

Cheers
Mark
