### ISSUE TITLE
Handle_json_error

### ISSUE THREAD

**Issue by kangh** [Esri/workforce-scripts#36]
**Describe the bug**
[2019-02-18 09:39:26,326] [create_assignments_from_csv.py:  75 -                           main()]             [MainThread] [      root] [    INFO] Authenticating...
[2019-02-18 09:39:31,184] [                 connection.py:1173 -             _handle_json_error()]             [MainThread] [arcgis._im] [   ERROR] You do not have permissions to access this resource or perform this operation.
[2019-02-18 09:39:31,184] [create_assignments_from_csv.py: 217 -                       <module>()]             [MainThread] [      root] [CRITICAL] Exception detected, script exiting
[2019-02-18 09:39:31,200] [create_assignments_from_csv.py: 218 -                       <module>()]             [MainThread] [      root] [CRITICAL] You do not have permissions to access this resource or perform this operation.
(Error Code: 403)
[2019-02-18 09:39:31,215] [create_assignments_from_csv.py: 219 -                       <module>()]             [MainThread] [      root] [CRITICAL] Traceback (most recent call last): |   File "C:\temp\workforce-scripts-master\scripts\create_assignments_from_csv.py", line 215, in <module> |     main(args) |   File "C:\temp\workforce-scripts-master\scripts\create_assignments_from_csv.py", line 82, in main |     item = gis.content.get(arguments.project_id) |   File "C:\Users\kangh\AppData\Local\ESRI\conda\envs\arcgispro-clone-new\lib\site-packages\arcgis\gis\__init__.py", line 3288, in get |     raise re |   File "C:\Users\kangh\AppData\Local\ESRI\conda\envs\arcgispro-clone-new\lib\site-packages\arcgis\gis\__init__.py", line 3283, in get |     item = self._portal.get_item(itemid) |   File "C:\Users\kangh\AppData\Local\ESRI\conda\envs\arcgispro-clone-new\lib\site-packages\arcgis\_impl\portalpy.py", line 1212, in get_item |     return self.con.post('content/items/' + itemid, self._postdata()) |   File "C:\Users\kangh\AppData\Local\ESRI\conda\envs\arcgispro-clone-new\lib\site-packages\arcgis\_impl\connection.py", line 1159, in post |     self._handle_json_error(resp_json['error'], errorcode) |   File "C:\Users\kangh\AppData\Local\ESRI\conda\envs\arcgispro-clone-new\lib\site-packages\arcgis\_impl\connection.py", line 1180, in _handle_json_error |     raise RuntimeError(errormessage) | RuntimeError: You do not have permissions to access this resource or perform this operation. | (Error Code: 403) |

**To Reproduce**
1. I am running the script create_assignments_from_csv.py from the Python Command Prompt. I created a clone of arcgispro-py3 in ArcGIS Pro 2.2.3 
2. Here is the command that I am running:
python C:\temp\workforce-scripts-master\scripts\create_assignments_from_csv.py 
-csv-file "../sample_data/assignments.csv" 
-u xxxxx 
-p xxxxx 
-org "https://xxxxx.maps.arcgis.com" 
-project-id "b973bac4f3794e2eacc975c315d88144" 
-x-field "xField" 
-y-field "yField" 
-assignment-type-field "Type" 
-location-field "Location" 
-description-field "Description" 
-priority-field "Priority" 
-work-order-id-field "Work Order Id" 
-due-date-field "Due Date" 
-attachment-file-field "Attachment" 
-wkid 102100 
-log-file "../log.txt" 
-worker-field "Worker" 
-timezone "US/Pacific"
3. I am using the sample assignments.csv to upload the assignments
4. 

**Expected behavior**
I am not even getting passed the very first step to run the script from the Python command prompt.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.x

**Additional context**

**Comment by apulverizer** [comment]
@kangh This error indicates to me that you don't have access to the specified item. This is the key error in  your stack trace:
>File "C:\temp\workforce-scripts-master\scripts\create_assignments_from_csv.py", line 82, in main | item = gis.content.get(arguments.project_id)

Can you verify the item id for the project you specified is correct? And that the user you are authenticating with via the script can access that item?

**Comment by kangh** [comment]
I had the wrong item id in my arguments. I am able to run the script successfully. Thank you very much.
