### ISSUE TITLE
Exceptions on migrate_assignments.py

### ISSUE THREAD

**Issue by ming800** [Esri/workforce-scripts#70]
**Describe the bug**
First time run migrate_assignments.py and two exceptions happened, both on "workforce.project" module.

on line 108, exception shows: 'Project' object has no attribute '_is_v2_project'.

Then, I changed to code to "if False:" and the exception happened on line 113: 
migrate_assignments.py:  98 -        main()][MainThread] [root] [    INFO] Authenticating...
migrate_assignments.py: 251 -    <module>()][MainThread] [root] [CRITICAL] Exception detected, script exiting
migrate_assignments.py: 252 -    <module>()][MainThread] [root] [CRITICAL] 'assignments'
migrate_assignments.py: 253 -    <module>()][MainThread] [root] [CRITICAL] Traceback (most recent call last): 
	|   File "G:/Development/workforce-scripts-master/scripts/migrate_assignments.py", line 249, in <module> 
	|     main(args) 
	|   File "G:/Development/workforce-scripts-master/scripts/migrate_assignments.py", line 114, in main 
	|     v2_project = workforce.Project(item2) 
	|   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\apps\workforce\project.py", line 45, in __init__ 
	|     self._assignment_schema = AssignmentSchema(self.assignments_layer) 
	|   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\_impl\common\_utils.py", line 158, in _lazy_property 
	|     setattr(self, attr_name, fn(self)) 
	|   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\apps\workforce\project.py", line 233, in assignments_layer 
	|     return FeatureLayer(self.assignments_layer_url, self.gis) 
	|   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\apps\workforce\project.py", line 183, in assignments_layer_url 
	|     return self._item_data['assignments']['url'] 
	| KeyError: 'assignments' |

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Python Version: 3.6

**Additional context**
I did not follow the steps to install the Python API 1.8.3+. Because I just upgraded my Pro to latest v.2.6.0 and it says the Python 1.8.3 will be installed with the Pro v 2.6.0

thanks,

Ming

**Comment by ming800** [comment]
It seams that my ArcGIS API is v 1.8.1 in stead of v 1.8.3+. However, when I open the Pro and try to update the package, it says the package is "up-to-date"!?

**Comment by ming800** [comment]
After updating the ArcGIS API for Python from v 1.8.1 to 1.8.3, it runs just fine!
