### ISSUE TITLE
Getting KeyError as "assignments" when using workforce with geoprocessing tool.

### ISSUE THREAD

**Issue by fatihenesusta** [Esri/workforce-scripts#97]
Hello,

I created a toolbox that works in local server but i could not make it work as a geoprocessing service.

My idea is that i want to be able to reach to workforce through using ArcGIS API and want to make operations over there by using the tool i created. It works without a problem on the ArcGIS Pro, but when i publish it as a geoprocessing device i get the following error.

 

Traceback (most recent call last): File "", line 71, in execute File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\apps\workforce\project.py", line 45, in __init__ self._assignment_schema = AssignmentSchema(self.assignments_layer) File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\_impl\common\_utils.py", line 158, in _lazy_property setattr(self, attr_name, fn(self)) File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\apps\workforce\project.py", line 233, in assignments_layer return FeatureLayer(self.assignments_layer_url, self.gis) File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\apps\workforce\project.py", line 183, in assignments_layer_url return self._item_data['assignments']['url'] KeyError: 'assignments' Failed to execute (Tool). Failed to execute (Tool). Failed.

What could be the reason?

**Comment by apulverizer** [comment]
I've seen this before if you specify the wrong item id when getting the item/project. Like if you specify the assignment layer item id when using a Workforce Classic Project instead of the Project item id. For the V2 (offline projects) you need to use the item id of the assignment feature layer.

**Comment by fatihenesusta** [comment]
> I've seen this before if you specify the wrong item id when getting the item/project. Like if you specify the assignment layer item id when using a Workforce Classic Project instead of the Project item id. For the V2 (offline projects) you need to use the item id of the assignment feature layer.

I actually saw your reply about it over here [https://github.com/Esri/workforce-scripts/issues/32](url)
I tried using workforce project id and as well as the assignment layer id but there still no luck. I tried to copy the ArcGISPro / apps / workforce folder to the ArcGISServer / apps / workforce it worked, but it was really slow and it server started to fail so i changed the folder back to the original one. 

I think the the name of the described fields are different on Enterprise and Online. I could not find a way to get over the problem except the way i described.

**Comment by apulverizer** [comment]
@fatihenesusta yeah I suspect ArcGIS Pro may be using a newer version of the Python API than what ArcGIS Server is using. I don't know if you can do anything about it on the server to upgrade (I'm guessing it's not supported).

**Comment by apulverizer** [comment]
Actually this should be possible if you follow the instructions here: https://enterprise.arcgis.com/en/server/latest/publish-services/windows/deploying-custom-python-packages.htm

**Comment by fatihenesusta** [comment]
> Actually this should be possible if you follow the instructions here: https://enterprise.arcgis.com/en/server/latest/publish-services/windows/deploying-custom-python-packages.htm

I will try this and keep you posted.

Thank you very much.

**Comment by fatihenesusta** [comment]
Hey, we can close this issue. I was able to upgrade to server to the latest version and i can access to the workforce. 

Thanks.
